### ISSUE TITLE
Params validation fails for post

### ISSUE THREAD

**Issue by alienxp03** [ruby-grape/grape#1093]
I'm having issue with the params validation when I'm using `post`. Just for this parth though. I've created some other APIs in other files, and it works fine. These are the file and errors that I got. 

`Entities::Person `
``` ruby
module Entities
  class Person < Grape::Entity
    expose :username, documentation: { type: 'string', desc: 'Username' }
    expose :email, documentation: { type: 'string', desc: 'Email' }
  end
end
```

<br/>
auth_api.rb
```` ruby
module Resources
  class AuthApi < Grape::API
    format :json

    desc 'Create a new user', {
      http_codes: [
        [201, 'Ok', Entities::Person],
        [202, 'Created and need email confirmation', Entities::PersonWithMessage],
        [400, 'Invalid request', Entities::Error]
      ]
    }
    params do
      requires :username, allow_blank: false, type: String, desc: 'Username for login'
      requires :password, allow_blank: false, type: String, desc: 'User password'
    end
    post do
      present attributes, with: Entities::Person
    end
  end
end
```

<br />
And I'll get the following error message.
``` ruby
NoMethodError at /api/people
============================

> Entities::Person missing attribute `username' on username is missing, password is missing

lib/rack_middleware/custom_domain_cookie.rb, line 20
----------------------------------------------------


   15         host = env["HTTP_HOST"].split(':').first 
   16       else
   17         host = nil
   18       end
   19       env["rack.session.options"][:domain] = custom_domain?(host) ? ".#{host}" : "#{@default_domain}"
>  20       return @app.call(env)
   21     end
   22   
   23     def custom_domain?(host)
   24       return false if host.nil?
   25       host !~ /#{@default_domain.sub(/^\./, '')}/i
```

<br />
However, if I change it to `get` instead of `post`, it will work just fine
``` ruby
{
  "error": "username is missing, password is missing"
}
```

<br/>
Gemfile
``` ruby
ruby '2.1.2'
gem 'rails', '3.2.21'
gem 'grape'
gem 'grape-entity'
gem 'grape-swagger'
gem 'swagger-ui_rails'
```


<br/>
Full stack trace
```
App backtrace
-------------

 - lib/rack_middleware/custom_domain_cookie.rb:20:in `call'

Full backtrace
--------------

 - grape-entity (0.4.5) lib/grape_entity/entity.rb:569:in `rescue in delegate_attribute'
 - grape-entity (0.4.5) lib/grape_entity/entity.rb:566:in `delegate_attribute'
 - grape-entity (0.4.5) lib/grape_entity/entity.rb:551:in `value_for'
 - grape-entity (0.4.5) lib/grape_entity/entity.rb:464:in `block in serializable_hash'
 - grape-entity (0.4.5) lib/grape_entity/entity.rb:462:in `serializable_hash'
 - grape (0.12.0) lib/grape/error_formatter/base.rb:52:in `present'
 - grape (0.12.0) lib/grape/error_formatter/json.rb:6:in `call'
 - grape (0.12.0) lib/grape/middleware/error.rb:88:in `format_message'
 - grape (0.12.0) lib/grape/middleware/error.rb:77:in `error_response'
 - grape (0.12.0) lib/grape/middleware/error.rb:32:in `block in call!'
 - grape (0.12.0) lib/grape/middleware/error.rb:57:in `exec_handler'
 - grape (0.12.0) lib/grape/middleware/error.rb:38:in `rescue in call!'
 - grape (0.12.0) lib/grape/middleware/error.rb:25:in `call!'
 - grape (0.12.0) lib/grape/middleware/base.rb:18:in `call'
 - rack (1.4.5) lib/rack/head.rb:9:in `call'
 - rack (1.4.5) lib/rack/builder.rb:134:in `call'
 - grape (0.12.0) lib/grape/endpoint.rb:196:in `call!'
 - grape (0.12.0) lib/grape/endpoint.rb:184:in `call'
 - rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in `block in call'
 - rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `block in recognize'
 - rack-mount (0.8.3) lib/rack/mount/code_generation.rb:68:in `optimized_each'
 - rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
 - rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in `call'
 - grape (0.12.0) lib/grape/api.rb:98:in `call'
 - grape (0.12.0) lib/grape/api.rb:33:in `call!'
 - grape (0.12.0) lib/grape/api.rb:29:in `call'
 - journey (1.0.4) lib/journey/router.rb:68:in `block in call'
 - journey (1.0.4) lib/journey/router.rb:56:in `call'
 - actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
 - omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
 - omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
 - omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
 - omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
 - meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
 - meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
 - lib/rack_middleware/custom_domain_cookie.rb:20:in `call'
 - warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
 - warden (1.2.3) lib/warden/manager.rb:34:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
 - rack (1.4.5) lib/rack/etag.rb:23:in `call'
 - rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
 - rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
 - rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
 - activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
 - activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
 - activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__1556445016926458498__call__3799515613831418921__callbacks'
 - activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
 - activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
 - activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
 - actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/reloader.rb:65:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
 - airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
 - rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
 - meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
 - lograge (0.3.2) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
 - railties (3.2.21) lib/rails/rack/logger.rb:18:in `call'
 - quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
 - actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
 - rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
 - rack (1.4.5) lib/rack/runtime.rb:17:in `call'
 - rack (1.4.5) lib/rack/lock.rb:15:in `call'
 - rack-livereload (0.3.15) lib/rack/livereload.rb:23:in `_call'
 - rack-livereload (0.3.15) lib/rack/livereload.rb:14:in `call'
 - actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
 - rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
 - airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
 - airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
 - railties (3.2.21) lib/rails/engine.rb:484:in `call'
 - railties (3.2.21) lib/rails/application.rb:231:in `call'
 - railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
 - rack (1.4.5) lib/rack/deflater.rb:13:in `call'
 - rack (1.4.5) lib/rack/content_length.rb:14:in `call'
 - railties (3.2.21) lib/rails/rack/log_tailer.rb:17:in `call'
 - rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
 - /Users/tokwan/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
 - /Users/tokwan/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
 - /Users/tokwan/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by dblock** [comment]
What's `attributes` in your context? Did you mean `params`?

**Comment by dblock** [comment]
You should bring this up on the mailing list, it doesn't look like a grape bug, just a usage question.

**Comment by alienxp03** [comment]
Just a follow up. I've managed to figured out the cause of the error. It was this line. Not so sure if it's a bug, but looks like one to me.

```[201, 'Ok', Entities::Person]``` will causes the error stack I've posted above. It will work if I change it to ```[200, 'Ok', Entities::Person]```. Looks like code ```201``` is causing the problem.

I'm also using ShareTribe, so if it's not grape bug, probably it's theirs is. Thanks btw :)

**Comment by dblock** [comment]
@alienxp03 This makes very little sense to me (I am not saying it's not a problem). Do you think you can construct a repro and post it to Github?

**Comment by alienxp03** [comment]
@dblock I'm using Sharetribe, along with this gem. My previous project was working fine though. So I guess it's probably it's because of Sharetribe. Since I'm the only who's having an issue with it, I guess it's fine. Also because I'm bit preoccupied at the moment, so gonna take some time before I can try to reproduce it. Anyway, thanks your help :)

**Comment by dblock** [comment]
I think you're guessing, it could be anything. Do reopen if you have a project that you can share that demonstrates this problem.

**Comment by alienxp03** [comment]
I've forked the Sharetribe repo and added `grape` and `grape-entity` gem to reproduce the error. Might need some configuration to get it running (need MySQL). I've made some notes on the README on how to reproduce the error I was talking about. Do let me know if you need anything else.

https://github.com/alienxp03/sharetribe
