### ISSUE TITLE
Default value error in nested parameters

### ISSUE THREAD

**Issue by Edison-Hsu** [ruby-grape/grape#1245]
I use default value in nested parameters like: 
```
optional :phone, type: Hash do
  requires :number, type: String, desc: 'phone number'
  optional :zone, type: String, default: '86', desc: 'phone zone'
  requires :password, type: String, desc: 'user password'
end
```

if I post form data by postman:
![screen shot 2016-01-15 at 4 24 17 pm](https://cloud.githubusercontent.com/assets/3348292/12348693/7b1bd574-bba4-11e5-9b64-bc78e8409c7c.png)

This is an exception, but grape was crashed
```
Unexpected error while processing request: no implicit conversion of Symbol into Integer
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/validations/validators/default.rb:18:in `[]'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/validations/validators/default.rb:18:in `block in validate!'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/validations/attributes_iterator.rb:20:in `block (2 levels) in each'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/validations/attributes_iterator.rb:16:in `each'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/validations/attributes_iterator.rb:16:in `each_with_index'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/validations/attributes_iterator.rb:16:in `block in each'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/validations/attributes_iterator.rb:15:in `each'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/validations/attributes_iterator.rb:15:in `each'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/validations/validators/default.rb:17:in `validate!'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/endpoint.rb:251:in `block (2 levels) in run'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/endpoint.rb:249:in `each'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/endpoint.rb:249:in `block in run'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/endpoint.rb:231:in `run'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/endpoint.rb:314:in `block in build_stack'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/middleware/base.rb:25:in `call!'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/middleware/base.rb:19:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/middleware/base.rb:25:in `call!'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/middleware/base.rb:19:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/middleware/error.rb:27:in `block in call!'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/middleware/error.rb:26:in `catch'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/middleware/error.rb:26:in `call!'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/middleware/base.rb:19:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/endpoint.rb:215:in `call!'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/endpoint.rb:209:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/api.rb:114:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/api.rb:44:in `call!'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/grape-0.14.0/lib/grape/api.rb:39:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/lib/thin/controllers/controller.rb:87:in `start'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/bin/thin:23:in `load'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/bin/thin:23:in `<main>'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/bin/ruby_executable_hooks:15:in `eval'
	/Users/user/.rvm/gems/ruby-2.3.0@api-service/bin/ruby_executable_hooks:15:in `<main>'

```

If I remove default value at zone parameter, it works and response error message
```
{
  "status": 400,
  "message": "phone is invalid, phone[number] is missing, phone[number] is invalid, phone[password] is missing, phone[password] is invalid"
}
```

I use grape version 0.14.0 and ruby 2.3.0, is this a bug or something else?

**Comment by dm1try** [comment]
>Unexpected error while processing request: no implicit conversion of Symbol into Integer`

This is definitely the bug. The wrong input shouldn't lead to such error.

>it works and response error message

Something is wrong with your input data, try write a spec.

**Comment by namusyaka** [comment]
By using this patch, the case can be avoided.

```diff
diff --git a/lib/grape/validations/validators/default.rb b/lib/grape/validations/validators/default.rb
index 7826ff1..2184b0f 100644
--- a/lib/grape/validations/validators/default.rb
+++ b/lib/grape/validations/validators/default.rb
@@ -15,7 +15,7 @@ module Grape

         attrs = AttributesIterator.new(self, @scope, params)
         attrs.each do |resource_params, attr_name|
-          if resource_params[attr_name].nil?
+          if resource_params.is_a?(Hash) && resource_params[attr_name].nil?
             validate_param!(attr_name, resource_params)
           end
         end
```

**Comment by dm1try** [comment]
@namusyaka we're waiting for a PR :bowtie:

**Comment by namusyaka** [comment]
@dm1try Of course. I've just opend a pull request.
