### ISSUE TITLE
rails rspec est :I got error  uninitialized constant RSpec::Rails (NameError)

### ISSUE THREAD

**Issue by rajcybage** [ruby-grape/grape#1272]
I have got error after in rspec rails app.

`````
C:\Sites\api_product>bundle exec rake spec
DL is deprecated, please use Fiddle
C:/RailsInstaller/Ruby2.1.0/bin/ruby.exe -I'C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib';'C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-support-3.4.1/lib' 'C
:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/exe/rspec' --pattern 'spec/**{,/*/**}/*_spec.rb'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core.rb:178:in `block in const_missing': uninitialized constant RSpec::Rails (NameError)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core.rb:178:in `fetch'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core.rb:178:in `const_missing'
        from C:/Sites/api_product/spec/spec_helper.rb:44:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core.rb:97:in `configure'
        from C:/Sites/api_product/spec/spec_helper.rb:20:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in `require'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in `block in requires='
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in `each'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1295:in `requires='
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:108:in `each'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration_options.rb:21:in `configure'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:105:in `setup'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:92:in `run'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in `run'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'

``````

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1273.
