### ISSUE TITLE
exactly_one_of seems not work for nested parameters

### ISSUE THREAD

**Issue by mmkhmk** [ruby-grape/grape#1288]
Hello,

I'm currently creating an API with the latest version(0.14.0) but exactly_one_of doesn't work as expected for nested parameters.

Here is the sample.

```
params do
  optional :additionalFacets, type: Hash do
    requires: label, type: String
    requires: facet, type: Hash do
      requires :field, type: String
      requires :type, type: String

      optional :limit, type: Integer
      optional :start, type: Integer

      exactly_one_of :limit, :start
    end
  end
end
```

In this case I meant the validation of exactly_one_of works only when additionalFacets are given.
But it works when it is not given as well.

Can you help check this?

**Comment by dblock** [comment]
It sounds like a bug, try writing a spec that reproduces this?

**Comment by mmkhmk** [comment]
Here is the spec that reproduces this.

```
context 'nested params in nested params' do
  before do
    subject.params do
      requires :nested, type: Hash do
        requires :nested_in_nested, type: Hash do
          optional :beer_nested
          optional :wine_nested
          optional :juice_nested
          exactly_one_of :beer_nested, :wine_nested, :juice_nested
        end
      end
      optional :nested2, type: Hash do
        requires :nested_in_nested2, type: Array do
          optional :beer_nested2
          optional :wine_nested2
          optional :juice_nested2
          exactly_one_of :beer_nested2, :wine_nested2, :juice_nested2
        end
      end
    end
    subject.get '/exactly_one_of_nested' do
      'exactly_one_of works!'
    end
  end

  it 'errors when none are present' do
    get '/exactly_one_of_nested'
    expect(last_response.status).to eq(400)
    expect(last_response.body).to eq 'nested is missing, nested[nested_in_nested] is missing, beer_nested, wine_nested, juice_nested are missing, exactly one parameter must be provided'
  end

  it 'succeeds when one is present' do
    get '/exactly_one_of_nested', nested: { nested_in_nested: { beer_nested: 'string' } }
    expect(last_response.status).to eq(200)
    expect(last_response.body).to eq 'exactly_one_of works!'
  end

  it 'errors when two or more are present' do
    get '/exactly_one_of_nested', nested: { nested_in_nested: { beer_nested: 'string' } }, nested2: { nested_in_nested2: [{ beer_nested2: 'string', wine_nested2: 'anotherstring' }] }
    expect(last_response.status).to eq(400)
    expect(last_response.body).to eq 'beer_nested2, wine_nested2 are mutually exclusive'
  end
end
```

Result
```
Failures:

  1) Grape::Validations params exactly one of nested params in a group errors when none are present
     Failure/Error: expect(last_response.body).to eq 'nested is missing, nested[nested_in_nested] is missing, beer_nested, wine_nested, juice_nested are missing, exactly one parameter must be provided'

       expected: "nested is missing, nested[nested_in_nested] is missing, beer_nested, wine_nested, juice_nested are missing, exactly one parameter must be provided"
            got: "nested is missing, nested[nested_in_nested] is missing, beer_nested, wine_nested, juice_nested are missing, exactly one parameter must be provided, beer_nested2, wine_nested2, juice_nested2 are missing, exactly one parameter must be provided"

       (compared using ==)
     # ./spec/grape/failed_validations_spec.rb:40:in `block (5 levels) in <top (required)>'

  2) Grape::Validations params exactly one of nested params in a group succeeds when one is present
     Failure/Error: expect(last_response.status).to eq(200)

       expected: 200
            got: 400

       (compared using ==)
     # ./spec/grape/failed_validations_spec.rb:45:in `block (5 levels) in <top (required)>'

Finished in 0.10893 seconds (files took 0.44235 seconds to load)
3 examples, 2 failures
```

**Comment by jlfaber** [comment]
I just tried this spec on both the current HEAD and v0.19.1 and it passes with no problem.

**Comment by dblock** [comment]
Closing, @mmkhmk if you can reproduce on HEAD please PR a failing spec.

**Comment by milgner** [comment]
I was just able to reproduce this with 1.0. See https://gist.github.com/milgner/d3c229c8dfd6670720403a92066f15f5 for a small, self-contained example. Find a zip of the full application with Gemfile etc at https://oc.illunis.net/index.php/s/ejXzHAYkCcojcCw

**Comment by dblock** [comment]
@milgner Can you PR a failing spec from that example on HEAD?

**Comment by dblock** [comment]
I'll reopen for now.

**Comment by milgner** [comment]
I have a couple of free days coming up, so that shouldn't be a problem :smile:

**Comment by milgner** [comment]
It looks like the problem might have been introduced in #1625, which changed the behaviour of `should_validate?`
