### ISSUE TITLE
uninitialized constant Grape::Formatter::Base (NameError)

### ISSUE THREAD

**Issue by scalp42** [ruby-grape/grape#1329]
I'm not sure where I should open the issue (see linked issue: https://github.com/ruby-grape/grape/issues/new) but running into the following with `berkshelf-api` (depending on `grape-msgpack`):

```
/opt/berkshelf-api # berks-api /opt/berkshelf-api/config.json
/usr/lib/ruby/gems/2.2.0/gems/grape-msgpack-0.1.2/lib/grape/msgpack.rb:39:in `<top (required)>': uninitialized constant Grape::Formatter::Base (NameError)
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/grape-msgpack-0.1.2/lib/grape-msgpack.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api/endpoint.rb:2:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api.rb:23:in `require_relative'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api.rb:23:in `<module:API>'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api.rb:10:in `<module:Berkshelf>'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api.rb:9:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api/srv_ctl.rb:72:in `start'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/lib/berkshelf/api/srv_ctl.rb:58:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/berkshelf-api-2.1.3/bin/berks-api:5:in `<top (required)>'
	from /usr/bin/berks-api:23:in `load'
	from /usr/bin/berks-api:23:in `<main>'
```

Any idea ? Much appreciated!

**Comment by scalp42** [comment]
Just tested with previous grape version `0.14.0` and it's working, so I believe `0.15.0` broke something.
