### ISSUE TITLE
Looks like latest Grape is not compatible with lastest Grape-Swagger?

### ISSUE THREAD

**Issue by atomless** [ruby-grape/grape#1369]
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate grape-swagger-0.20.1, because grape-0.16.2 conflicts with grape (<= 0.14.0, >= 0.12.0) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Users/jamestindall/Documents/doc_baton/BatonSite/dist/server/api/api.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/jamestindall/Documents/doc_baton/BatonSite/dist/config.ru:6:in `block in <main>'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /Users/jamestindall/Documents/doc_baton/BatonSite/dist/config.ru:in `new'
	from /Users/jamestindall/Documents/doc_baton/BatonSite/dist/config.ru:in `<main>'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
	from /usr/bin/rackup:23:in `load'
	from /usr/bin/rackup:23:in `<main>'
```

**Comment by dblock** [comment]
Please see https://github.com/ruby-grape/grape-swagger#compatibility.

**Comment by atomless** [comment]
Oh, so in order to use latest Grape you must use swagger 0.11!? Will future versions of swagger support latest Grape or will it only be that old 0.11 version?

**Comment by dblock** [comment]
Not sure. We're trying to expand the matrix and could use some help!
