### ISSUE TITLE
helpers behaviour inconsistency

### ISSUE THREAD

**Issue by etehtsea** [ruby-grape/grape#1418]
``` ruby
class Child < Grape::API
  get do
    method_available
    params[:expand] && params[:expand][:ololo]
  end
end

class Root < Grape::API
  module SharedParams
    extend Grape::API::Helpers

    def method_available
      puts "WOO"
    end

    params :expand do
      requires :ololo
    end
  end

  helpers SharedParams

  mount Child
end

p Rack::MockRequest.new(Child).get('/').body
# >> WOO
# ""
# => true
```

So helpers methods used in parent class are available in mounted endpoint and `params` obviously aren't. I find this behaviour a little  inconsistent.

**Comment by dblock** [comment]
These params don't just automatically carry onto endpoints, you have to `use :expand` in the endpoint's `params`. Does that work?

**Comment by etehtsea** [comment]
Haha, stupid me, sorry. Completely forgot about it, sorry.

**Comment by dblock** [comment]
Glad this helped. There're no stupid questions!

**Comment by etehtsea** [comment]
Hmmm, I recalled the issie. It don't seem to work:

```ruby
```ruby
class Child < Grape::API
  params { use :expand }

  get do
    method_available
    params[:expand] && params[:expand][:ololo]
  end
end

class Root < Grape::API
  module SharedParams
    extend Grape::API::Helpers

    def method_available
      puts "WOO"
    end

    params :expand do
      requires :ololo
    end
  end

  helpers SharedParams

  mount Child
end
```

```
  from /tmp/demo_helpers.rb:1:in `<top (required)>'
  from (irb):1:in `load'
  from (irb):1
  from /Users/kes/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
>> RuntimeError: Params :expand not found!
  from /Users/kes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/dsl/parameters.rb:37:in `block (2 levels) in use'
  from /Users/kes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/dsl/parameters.rb:36:in `fetch'
  from /Users/kes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/dsl/parameters.rb:36:in `block in use'
  from /Users/kes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/dsl/parameters.rb:35:in `each'
  from /Users/kes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/dsl/parameters.rb:35:in `use'
  from /tmp/demo_helpers.rb:4:in `block in <class:Child>'
  from /Users/kes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/validations/params_scope.rb:30:in `instance_eval'
  from /Users/kes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/validations/params_scope.rb:30:in `initialize'
  from /Users/kes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/dsl/validations.rb:23:in `new'
  from /Users/kes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-0.16.2/lib/grape/dsl/validations.rb:23:in `params'
  from /tmp/demo_helpers.rb:4:in `<class:Child>'
  from /tmp/demo_helpers.rb:3:in `<top (required)>'
  from (irb):2:in `load'
  from (irb):2
  from /Users/kes/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

**Comment by dblock** [comment]
This looks broken. I would turn it into a spec next.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/issues/1420, @etehtsea lmk if I missed anything.
