### ISSUE TITLE
Params Integer dont work

### ISSUE THREAD

**Issue by Ogromny** [ruby-grape/grape#1462]
```ruby
        params do
            requires :title, type: String
            requires :content, type: String
            requires :expiration, types: Integer
        end
        put '/pasta/' do
            {title: declared(params[:title]),
             content: declared(params[:content]),
             expiration: declared(params[:expiration])}
        end
```
```bash
curl -X PUT -H "Content-Type: application/json" localhost:4567/1.0/pasta/ -d '{"title": "Manifeste", "content": "Marx", "expiration":2}'
```

return me an error 
```bash
TypeError: no implicit conversion of Symbol into Integer
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/dsl/inside_route.rb:53:in `[]'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/dsl/inside_route.rb:53:in `block (2 levels) in declared'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/dsl/inside_route.rb:44:in `each_pair'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/dsl/inside_route.rb:44:in `block in declared'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/dsl/inside_route.rb:41:in `each'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/dsl/inside_route.rb:41:in `each_with_object'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/dsl/inside_route.rb:41:in `declared'
	/home/ogromny/Code/RUBY/PastaBin/api/pastabin.rb:20:in `block in <class:API>'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/endpoint.rb:66:in `call'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/endpoint.rb:66:in `block (2 levels) in generate_api_method'
	/home/ogromny/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/endpoint.rb:65:in `block in generate_api_method'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/endpoint.rb:238:in `block in run'
	/home/ogromny/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/endpoint.rb:219:in `run'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/endpoint.rb:285:in `block in build_stack'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/middleware/base.rb:30:in `call!'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/middleware/base.rb:23:in `call'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/middleware/base.rb:30:in `call!'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/middleware/base.rb:23:in `call'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/middleware/error.rb:29:in `block in call!'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/middleware/error.rb:28:in `catch'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/middleware/error.rb:28:in `call!'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/middleware/base.rb:23:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/endpoint.rb:203:in `call!'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/endpoint.rb:197:in `call'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/router/route.rb:68:in `exec'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:63:in `block in identity'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:84:in `transaction'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:59:in `identity'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:44:in `block in call'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:107:in `with_optimization'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/router.rb:43:in `call'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/api.rb:112:in `call'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/api.rb:45:in `call!'
	/home/ogromny/.gem/ruby/2.3.0/gems/grape-0.16.2/lib/grape/api.rb:40:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/home/ogromny/.gem/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
	/home/ogromny/.gem/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
	/home/ogromny/.gem/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
	/home/ogromny/.gem/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:53:in `process'
	/home/ogromny/.gem/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:39:in `receive_data'
	/home/ogromny/.gem/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
	/home/ogromny/.gem/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
	/home/ogromny/.gem/ruby/2.3.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
	/home/ogromny/.gem/ruby/2.3.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
	/usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
	/usr/bin/rackup:23:in `load'
	/usr/bin/rackup:23:in `<main>'
::1 - - [27/Jul/2016:15:55:30 +0200] "PUT /1.0/pasta/ HTTP/1.1" 500 257513 0.0820
```

I can't figure where the probleme sits...

Thanks in advance, I'm French so sorry for my english

**Comment by jlfaber** [comment]
Looks like your syntax for accessing `declared` isn't quite right.  Try this instead:
````ruby
        put '/pasta/' do
            {title: declared(params).title,
             content: declared(params).content,
             expiration: declared(params).expiration}
        end
````

**Comment by Ogromny** [comment]
Thanks ! Now it's working :)
