### ISSUE TITLE
Hashie 3.4.5 re-defines Array type? 

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#1494]
```
Failures:

  1) Grape::Validations::CoerceValidator coerce multiple types for primitive collections allows singular form declaration
     Failure/Error: expect(last_response.body).to eq('["the", "other"]')

       expected: "[\"the\", \"other\"]"
            got: "#<Hashie::Array [\"the\", \"other\"]>"

       (compared using ==)
     # ./spec/grape/validations/validators/coerce_spec.rb:628:in `block (5 levels) in <top (required)>'

  2) Grape::Validations::CoerceValidator coerce multiple types for primitive collections allows multiple collection types
     Failure/Error: expect(last_response.body).to eq('[1, 2, 3]')

       expected: "[1, 2, 3]"
            got: "#<Hashie::Array [1, 2, 3]>"

       (compared using ==)
     # ./spec/grape/validations/validators/coerce_spec.rb:642:in `block (5 levels) in <top (required)>'

  3) Grape::Validations::CoerceValidator coerce multiple types for primitive collections allows collections with multiple types
     Failure/Error: expect(last_response.body).to eq('[1, 2, "true", "three"]')

       expected: "[1, 2, \"true\", \"three\"]"
            got: "#<Hashie::Array [1, 2, \"true\", \"three\"]>"

       (compared using ==)
     # ./spec/grape/validations/validators/coerce_spec.rb:656:in `block (5 levels) in <top (required)>'
```

**Comment by towanda** [comment]
@dblock this seems to be fixed by https://github.com/intridea/hashie/issues/367, could you please close this?

**Comment by dblock** [comment]
That's just related, in Grape https://github.com/ruby-grape/grape/commit/0d645124da9157bf38703b1e8450b6125463b14e worked around this.
