### ISSUE TITLE
Stacklevel to deep error

### ISSUE THREAD

**Issue by tonobo** [ruby-grape/grape#1683]
Heyho guys,

we're experienced an issue since the new `1.0.1` release. 

The line where is issue happend.
```ruby
class BaseController # inherits from Grape::API
   # Controller::LDAP will inherit from BaseController  
   mount Controller::LDAP # <- Error happens here
end
```

Trace:
```
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/endpoint.rb:113:in `inherit_settings'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/api.rb:94:in `block in inherit_settings'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/api.rb:93:in `each'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/api.rb:93:in `inherit_settings'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/dsl/routing.rb:89:in `block in mount'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/dsl/routing.rb:82:in `each_pair'
# /usr/local/bundle/gems/grape-1.0.1/lib/grape/dsl/routing.rb:82:in `mount'
# ./lib/e/bootserver_api.rb:53:in `block in <module:BootserverApi>'
# ./lib/e/bootserver_api.rb:32:in `class_eval'
# ./lib/e/bootserver_api.rb:32:in `<module:BootserverApi>'
```
Gem diff:
```diff
timmy@tonobo-top  >>> diff /tmp/_a.diff /tmp/_b.diff
15c15
< Using grape 1.0.1
---
> Using grape 1.0.0
33,34c33,34
< Using oj 3.3.6
< Using pry 0.11.0
---
> Using oj 3.3.5
> Using pry 0.10.4
48c48
< Using simplecov 0.15.1
---
> Using simplecov 0.15.0
49a50
> Using slop 3.6.0
```

**Comment by tonobo** [comment]
The issue possibly introduced here -> https://github.com/ruby-grape/grape/compare/v1.0.0...v1.0.1#diff-1e79b22ac5b0ad79f2de0534749082e6

**Comment by dblock** [comment]
Care to spec it, maybe a fix?

**Comment by tonobo** [comment]
This will basically reproduce it.

```ruby
require 'grape'

class BaseController < Grape::API

end

class MooController < BaseController

end

BaseController.class_eval do
  mount MooController
end
```

```
/root/.gem/ruby/2.3.0/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:15:in `[]': stack level too deep (SystemStackError)
	from /root/.gem/ruby/2.3.0/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
	from /root/.gem/ruby/2.3.0/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
	from /root/.gem/ruby/2.3.0/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
	from /root/.gem/ruby/2.3.0/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
	from /root/.gem/ruby/2.3.0/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
	from /root/.gem/ruby/2.3.0/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
	from /root/.gem/ruby/2.3.0/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
	from /root/.gem/ruby/2.3.0/gems/grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]'
	 ... 9349 levels...
	from /root/.gem/ruby/2.3.0/gems/grape-1.0.1/lib/grape/dsl/routing.rb:82:in `mount'
	from base_controller.rb:12:in `block in <main>'
	from base_controller.rb:11:in `class_eval'
	from base_controller.rb:11:in `<main>'
```

**Comment by tonobo** [comment]
Any updates?

**Comment by dm0reau** [comment]
Hi,

I've handled a similar problem, with a parent "Base" class mounting each other like this:

```ruby
class API::Base < Grape::API
  format :json
  # This probably causes an infinite recursion
  mount API::Tasks
end

class API::Tasks < API::Base
  # Resource code...
end

# config/routes.rb
mount API::Base => '/api'
```

I've resolved it with a mounted "Root" class like this:

```ruby
class API::Root < Grape::API
  mount API::Tasks
end

class API::Base < Grape::API
  format :json
end

class API::Tasks < API::Base
  # Resource code...
end

# config/routes.rb
mount API::Root => '/api'
```

Hoping it will help.

**Comment by dblock** [comment]
@tonobo What kind of update are you looking for?

**Comment by tonobo** [comment]
Isn't it a bug? It hast been appeared in 1.0.1. Will it fixed?

**Comment by dblock** [comment]
Looks like a bug. Will gladly take a fix in a pull request from you, thanks.

**Comment by tonobo** [comment]
Ok, i'll take a look at it on monday

**Comment by peterwillcn** [comment]
I get similar issue
grape-1.0.1/lib/grape/util/stackable_values.rb:18:in `[]': stack level too deep (SystemStackError)

**Comment by jeyraof** [comment]
any updates?
I encountered same problem.

**Comment by cbilgili** [comment]
I encountered same problem, just commented out route mounting for a while to step over it.

**Comment by saifis** [comment]
Not sure if this is the same problem, but I had the same error, turns out several initial setup stuff has changed, like Base::API changing to Grape::API and several other namespace changes, it could be a straight out bug, I got it fixed up by looking over the setup area of the top page, hope it helps.

**Comment by jkowens** [comment]
I've put together PR #1727 that should resolve this issue, if any are able to take a look.
