### ISSUE TITLE
uninitialized constant Grape::Env rails5 upgrade

### ISSUE THREAD

**Issue by pedrocaseiro** [ruby-grape/grape#1732]
After upgrading from to Rails 5, some of my tests randomly fail with the error down below. They don't always fail, its just that this error appears from time to time.

```
1.2) Failure/Error: routing_args = env[Grape::Env::GRAPE_ROUTING_ARGS]

          NameError:
            uninitialized constant Grape::Env
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-1.0.1/lib/grape/router.rb:117:in `process_route'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-1.0.1/lib/grape/router.rb:74:in `block in identity'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-1.0.1/lib/grape/router.rb:93:in `transaction'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-1.0.1/lib/grape/router.rb:72:in `identity'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-1.0.1/lib/grape/router.rb:57:in `block in call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-1.0.1/lib/grape/router.rb:135:in `with_optimization'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-1.0.1/lib/grape/router.rb:56:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-1.0.1/lib/grape/api.rb:119:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-1.0.1/lib/grape/api.rb:45:in `call!'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/grape-1.0.1/lib/grape/api.rb:40:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/mapper.rb:46:in `serve'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/journey/router.rb:39:in `block in serve'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/journey/router.rb:26:in `each'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/journey/router.rb:26:in `serve'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb:727:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-cors-1.0.1/lib/rack/cors.rb:93:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/remotipart-1.3.1/lib/remotipart/middleware.rb:32:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/cookies.rb:613:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/callbacks.rb:90:in `run_callbacks'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/airbrake-7.0.0/lib/airbrake/rack/middleware.rb:52:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:36:in `call_app'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:24:in `block in call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:26:in `tagged'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `tagged'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:24:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/request_id.rb:24:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/static.rb:136:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:522:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/capybara-2.6.2/lib/capybara/server.rb:19:in `call'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
          # /home/vagrant/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
          #
          #   Showing full backtrace because every line was filtered out.
          #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
          #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
```

**Comment by dm1try** [comment]
I've looked at the initial implementation in #980 and did not find the trigger for "eager" loading.

the docs [say](http://api.rubyonrails.org/classes/ActiveSupport/Autoload.html#method-i-autoload) that we should explicitly call `.eager_load!`
or for Rails, we could use `eager_load_namespaces` config option as mentioned in the referenced article

@pedrocaseiro could you try to set 
```ruby
    # config/application.rb
    config.eager_load_namespaces << Grape
```
and report if this helps

cc @dblock

**Comment by pedrocaseiro** [comment]
I'll try and i'll give feedback as soon as possible. Since it just happens sometimes in random tests it's hard to know if it's fixed :(
