### ISSUE TITLE
Grape::Middleware::Versioner::Header breaks

### ISSUE THREAD

**Issue by frank184** [ruby-grape/grape#1770]
Upgrading to Grape >= 0.14.0 crashes our some of our requests. 

```
undefined method `[]' for nil:NilClass
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/versioner/header.rb:181:in `request_vendor'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/versioner/header.rb:123:in `block in headers_contain_wrong_vendor?'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/versioner/header.rb:122:in `each'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/versioner/header.rb:122:in `all?'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/versioner/header.rb:122:in `headers_contain_wrong_vendor?'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/versioner/header.rb:37:in `before'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/base.rb:29:in `call!'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/base.rb:24:in `call'
~/.rvm/gems/ruby-2.3.7/gems/warden-1.2.7/lib/warden/manager.rb:32:in `call'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/error.rb:37:in `block in call!'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/error.rb:36:in `catch'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/error.rb:36:in `call!'
~/.rvm/gems/ruby-2.3.7/gems/grape-1.0.3/lib/grape/middleware/base.rb:24:in `call'
~/.rvm/gems/ruby-2.3.7/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
```

The issue seems related to the Regex that captures the vendor within Middleware Versioner Headers.
Our application uses a Warden middleware, which is raising this exception.

`VENDOR_VERSION_HEADER_REGEX = /\Avnd\.([a-z0-9.\-_!#\$&\^]+?)(?:-([a-z0-9*.]+))?(?:\+([a-z0-9*\-.]+))?\z/`

The Middleware raises an exception caused by the Regex not matching.

```
# https://github.com/ruby-grape/grape/blob/v0.14.0/lib/grape/middleware/versioner/header.rb#L181
subtype.match(VENDOR_VERSION_HEADER_REGEX)[1]
```

Any suggestion would be appreciated.

# Edit

Unfortunately some of our requests used underscores in the format, which would lead to the chain of lazy matching breaking and making everything unmatched (i.e. vendor).

`vnd.mycompany-v1.custom_format`

**Comment by dblock** [comment]
Is this a bug in Grape though? I mean is that vendor string valid in which case do we need to fix it in the code?

**Comment by frank184** [comment]
The vendor is valid, it's the lazy matching of Regex that prevented it from matching because of the format/extension with an underscore.
