### ISSUE TITLE
Validation Error is not raised when optional Hash type parameter is received String type value and exactly_one_of be used

### ISSUE THREAD

**Issue by woshidan** [ruby-grape/grape#1821]
Gem versions:

- Rack 2.0.6
- Grape 1.1.0

I defined the API as below and expected to return a 400 error when the memo parameter is String type value instead of a Hash type value, but 500 error returned.

```ruby
require 'grape'

module TestApp
  class API < Grape::API

    params do
      requires :schedule, type: Hash do
        requires :participants, type: Array[String]
      end

      optional :memo, type: Hash do
        optional :text,   type: String
        optional :image_url, type: String

        optional :custom_body, type: Hash, coerce_with: JSON

        exactly_one_of :text, :custom_body
        exactly_one_of :image_url, :custom_body
      end
    end

    post "/" do
      # do something
    end
  end
end

run TestApp::API
```

Here is examples of test request and the responses.

### CASE 1

```sh
curl localhost:9292/ --request POST \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data-binary '{ "schedule": { "participants": [ "Tom", "Bob"]}, "memo" : { "text": "HOGEHOGE", "image_url": "http://example.com/images/001.jpg" } }'
```

```
status code: 201, response: null
```

```sh
curl localhost:9292/ --request POST \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data-binary '{ "schedule": { "participants": [ "Tom", "Bob"]}, "memo" : {"custom_body": "{ \"xxx\": \"yyy\" }" } }'
```

```
status code: 201, response: null
```

### CASE 2

```sh
curl localhost:9292/ --request POST \
--header "Content-Type: application/json" \
--data-binary '{ "schedule": { "participants": [ "Tom", "Bob"]}, "memo" : {"custom_body": "HOGE"} }'
```

```
status code: 400, response: {"error":"memo[custom_body] is invalid"}
```

### CASE 3

```sh
curl localhost:9292/ --request POST \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
--data-binary '{ "schedule": { "participants": [ "Tom", "Bob"]}, "memo" : { "text": "HOGEHOGE", "image_url": "http://example.com/images/001.jpg", "custom_body": "{ \"xxx\": \"yyy\" }" } }'
```

```
status code: 400, response: {"error":"text, custom_body are mutually exclusive, image_url, custom_body are mutually exclusive"}
```

### CASE 4

```sh
curl localhost:9292/ --request POST \
--header "Content-Type: application/json" \
--data-binary '{ "schedule": { "participants": [ "Tom", "Bob"]}, "memo" : "{\"custom_body\": \"HOGE\"}" }'
```

```
status code: 500
response:
NoMethodError: undefined method `any?' for "{\"custom_body\": \"HOGE\"}":String
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/validations/validators/multiple_params_base.rb:14:in `any?'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/validations/validators/multiple_params_base.rb:14:in `scope_requires_params'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/validations/validators/exactly_one_of.rb:7:in `validate!'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/validations/validators/base.rb:29:in `validate'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/endpoint.rb:349:in `block (2 levels) in run_validators'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/endpoint.rb:347:in `each'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/endpoint.rb:347:in `block in run_validators'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/endpoint.rb:346:in `run_validators'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/endpoint.rb:260:in `block in run'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/endpoint.rb:243:in `run'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/endpoint.rb:313:in `block in build_stack'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/middleware/base.rb:31:in `call!'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/middleware/base.rb:24:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/middleware/error.rb:38:in `block in call!'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/middleware/error.rb:37:in `catch'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/middleware/error.rb:37:in `call!'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/middleware/base.rb:24:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/endpoint.rb:227:in `call!'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/endpoint.rb:221:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/router/route.rb:72:in `exec'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/router.rb:121:in `process_route'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/router.rb:74:in `block in identity'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/router.rb:93:in `transaction'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/router.rb:72:in `identity'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/router.rb:57:in `block in call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/router.rb:137:in `with_optimization'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/router.rb:56:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/api.rb:119:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/api.rb:45:in `call!'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/grape-1.1.0/lib/grape/api.rb:40:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/lint.rb:49:in `_call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/lint.rb:37:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/show_exceptions.rb:23:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/chunked.rb:54:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/content_length.rb:15:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
	/Users/woshidan/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

Does anyone know? I think that it is similar to https://github.com/ruby-grape/grape/issues/1288, but exactly_one_of validator is working in this API from the result of CASE 3.

**Comment by dblock** [comment]
Looks like a bug, you should turn it into a spec + fix.

**Comment by dblock** [comment]
Merged
