### ISSUE TITLE
Undefined method 'merge' for empty hash

### ISSUE THREAD

**Issue by shlima** [ruby-grape/grape#1925]
```ruby
# works
present :aggregations, []

# raises an <NoMethodError: undefined method `merge' for :aggregations:Symbol>
present :aggregations, {}
```

```
"Framework Trace": [
      {
        "exception_object_id": 70108428652700,
        "id": 0,
        "trace": "grape (1.2.4) lib/grape/dsl/inside_route.rb:332:in `present'"
      },
      {
        "exception_object_id": 70108428652700,
        "id": 2,
        "trace": "grape (1.2.4) lib/grape/endpoint.rb:57:in `call'"
      },
      {
        "exception_object_id": 70108428652700,
        "id": 3,
        "trace": "grape (1.2.4) lib/grape/endpoint.rb:57:in `block (2 levels) in generate_api_method'"
      },
      {
        "exception_object_id": 70108428652700,
        "id": 4,
        "trace": "activesupport (6.0.0) lib/active_support/notifications.rb:182:in `instrument'"
      },
      {
        "exception_object_id": 70108428652700,
        "id": 5,
        "trace": "grape (1.2.4) lib/grape/endpoint.rb:56:in `block in generate_api_method'"
      },
      {
        "exception_object_id": 70108428652700,
        "id": 6,
        "trace": "grape (1.2.4) lib/grape/endpoint.rb:263:in `block in run'"
      },
      {
        "exception_object_id": 70108428652700,
        "id": 7,
        "trace": "activesupport (6.0.0) lib/active_support/notifications.rb:182:in `instrument'"
      },
```

**Comment by shlima** [comment]
I've made a temp solution:

```ruby
present :aggregations, search.aggregations, with: GrapeHashSerializer
```

```ruby
# frozen_string_literal: true

class GrapeHashSerializer
  def self.represent(hash, *)
    hash
  end
end
```

**Comment by dblock** [comment]
What's the stack for this error?

Try writing a unit test in Grape?

**Comment by elliotcm** [comment]
For future searchers, the issue here is that `present :x, {}` treats the `{}` as a set of options, so instead of `:x` being the key and `{}` being the object, `:x` becomes the object.

Quick fix if you need to explicitly present an empty object is `present :x, {}, {}`.
