### ISSUE TITLE
`cascade?` in router.rb raising NoMethodError after upgrade past 1.10.0

### ISSUE THREAD

**Issue by subvertallchris** [ruby-grape/grape#1990]
Been using 1.10.0 and previous versions happily but an upgrade to 1.20.0 or beyond breaks all of my tests that make use of ActionDispatch's standard REST action methods. For example, a simple post:

```
post '/working-endpoint', params: { id: 123 }
```

will raise:

```
NoMethodError:
         undefined method `[]' for nil:NilClass
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/router.rb:163:in `cascade?'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/router.rb:95:in `transaction'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/router.rb:72:in `identity'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/router.rb:57:in `block in call'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/router.rb:137:in `with_optimization'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/router.rb:56:in `call'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/api/instance.rb:127:in `call'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/api/instance.rb:53:in `call!'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/api/instance.rb:48:in `call'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/api.rb:106:in `block in add_setup'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/api.rb:105:in `each'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/api.rb:105:in `add_setup'
       # ./vendor/cache/ruby/2.6.0/gems/grape-1.2.0/lib/grape/api.rb:36:in `block (2 levels) in override_all_methods!'
       # ./vendor/cache/ruby/2.6.0/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
       # ./vendor/cache/ruby/2.6.0/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/mapper.rb:46:in `serve'
       # ./vendor/cache/ruby/2.6.0/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
       # ./vendor/cache/ruby/2.6.0/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:33:in `each'
       # ./vendor/cache/ruby/2.6.0/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:33:in `serve'
       # ./vendor/cache/ruby/2.6.0/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:844:in `call'
```

There's a lot more to the stack trace if you're interested.

The failing method looks like this:

```
    def cascade?(response)
      response && response[1][Grape::Http::Headers::X_CASCADE] == 'pass'
    end
```

Digging into it, I can see that `response` is an array but it only has one element (an instance of `Rack::Response`) so a call to `response[1]` will always fail. Up above, I see a `default_response` method:

```
    def default_response
      [404, { Grape::Http::Headers::X_CASCADE => 'pass' }, ['404 Not Found']]
    end
```

I'm guessing that's the format it expects for the response. I poked around a bit more but couldn't quite pin down where the response I'm getting is actually coming from or why it's wrong. If someone could help me fix this, I'd really appreciate it. This upgrade is pretty important and I'm totally blocked at the moment.

**Comment by subvertallchris** [comment]
Looks like it's [this](https://github.com/ruby-grape/grape/issues/1966) that's biting me, downgrading to Rack 2.0.8 seems to have done the trick. Insanely frustrating. I can't upgrade to 1.3.0 yet, the new type coercion dies on coercions of deeply nested arrays like `Array[Array[Float]]`.
