### ISSUE TITLE
Array[Array[X]] Error

### ISSUE THREAD

**Issue by braktar** [ruby-grape/grape#2041]
While upgrading from version 1.2.5 to 1.3.2 I figure out that the coerce of type Array[Array[String]]  or Array[Array[Integer]] turns into the following error : 

```
Failure/Error: MAPPING.fetch(type) { scope.const_get(type.name) }

     NoMethodError:
       undefined method `name' for [String]:Array
     # ./lib/grape/validations/types/primitive_coercer.rb:33:in `block in initialize'
     # ./lib/grape/validations/types/primitive_coercer.rb:33:in `fetch'
     # ./lib/grape/validations/types/primitive_coercer.rb:33:in `initialize'
     # ./lib/grape/validations/types/array_coercer.rb:21:in `new'
     # ./lib/grape/validations/types/array_coercer.rb:21:in `initialize'
     # ./lib/grape/validations/types/build_coercer.rb:64:in `new'
     # ./lib/grape/validations/types/build_coercer.rb:64:in `create_coercer_instance'
     # ./lib/grape/validations/types/build_coercer.rb:40:in `block in build_coercer'
     # ./lib/grape/validations/types/build_coercer.rb:77:in `cache_instance'
     # ./lib/grape/validations/types/build_coercer.rb:39:in `build_coercer'
     # ./lib/grape/validations/validators/coerce.rb:26:in `initialize'
     # ./lib/grape/validations/validator_factory.rb:7:in `new'
     # ./lib/grape/validations/validator_factory.rb:7:in `create_validator'
     # ./lib/grape/endpoint.rb:362:in `block in run_validators'
     # ./lib/grape/endpoint.rb:362:in `map'
     # ./lib/grape/endpoint.rb:362:in `run_validators'
     # ./lib/grape/endpoint.rb:262:in `block in run'
     # ./lib/grape/endpoint.rb:245:in `run'
     # ./lib/grape/endpoint.rb:320:in `block in build_stack'
     # ./lib/grape/middleware/base.rb:35:in `call!'
     # ./lib/grape/middleware/base.rb:28:in `call'
     # ./lib/grape/middleware/error.rb:39:in `block in call!'
     # ./lib/grape/middleware/error.rb:38:in `catch'
     # ./lib/grape/middleware/error.rb:38:in `call!'
     # ./lib/grape/middleware/base.rb:28:in `call'
     # ./lib/grape/endpoint.rb:229:in `call!'
     # ./lib/grape/endpoint.rb:223:in `call'
     # ./lib/grape/router/route.rb:76:in `exec'
     # ./lib/grape/router.rb:136:in `process_route'
     # ./lib/grape/router.rb:89:in `block in identity'
     # ./lib/grape/router.rb:108:in `transaction'
     # ./lib/grape/router.rb:87:in `identity'
     # ./lib/grape/router.rb:72:in `block in call'
     # ./lib/grape/router.rb:152:in `with_optimization'
     # ./lib/grape/router.rb:71:in `call'
     # ./lib/grape/api/instance.rb:167:in `call'
     # ./lib/grape/api/instance.rb:71:in `call!'
     # ./lib/grape/api/instance.rb:66:in `call'
     # ./lib/grape/api.rb:68:in `call'
     # ./spec/support/array_array.rb:7:in `block (3 levels) in <top (required)>'
     # ./spec/support/array_array.rb:35:in `block (4 levels) in <top (required)>'
```

Here is a spec to reproduce the above error. The issue appears into version 1.3.0.
```
# frozen_string_literal: true

require 'spec_helper'

describe Grape::Validations::DefaultValidator do
  describe '#validate!' do
    subject(:validate) { post path, params }

    module ValidationsSpec
      module DefaultValidatorSpec
        class API < Grape::API
          rescue_from Grape::Exceptions::ValidationErrors do |e|
            error!(e.errors.transform_keys! { |key| key.join(',') }, 400)
          end

          params do
            requires :skills, type: Array[Array[String]]
            optional :matrix, type: Array[Array[Integer]]
          end

          post '/array-array-type' do
          end
        end
      end
    end

    def app
      ValidationsSpec::DefaultValidatorSpec::API
    end

    context 'array of array of string should be correctly coerced.' do
      let(:path) { '/array-array-type' }
      let(:params) do
        {
          skills: [%w[a b]],
          matrix: [[0, 1], [1, 0]]
        }
      end

      it 'It should return array of array of string' do
        validate
        expect(JSON.parse(last_response.body)).to eq(
          'skills' => [%w[a b]],
          'matrix' => [[0, 1], [1, 0]]
        )
      end
    end
  end
end
```

**Comment by dblock** [comment]
Please try HEAD, https://github.com/ruby-grape/grape/pull/2054

**Comment by braktar** [comment]
It fixes the issue, both for nest arrays of Integer and String

**Comment by ericproulx** [comment]
That's unfortunate, I'll take a look

**Comment by AlexWayfer** [comment]
> That's unfortunate, I'll take a look

Thank you. I understand that it'd be better to create a new issue, but I was not sure how it's an issue and it has work-around with custom validators.
