### ISSUE TITLE
Ruby 3 breaks basic auth

### ISSUE THREAD

**Issue by hkockerbeck** [ruby-grape/grape#2147]
The following seems to work fine with Ruby 3.0.0-p0 and grape 1.5.1
```ruby
# frozen_string_literal: true

require 'grape'

# api module
module Api
  # api class
  class API < Grape::API
    version 'v1', using: :header, vendor: 'my_api'
    format :json
    prefix :api

    resource :status do
      desc 'Some description'
      get do
        Time.now
      end
    end
  end
end
```

but when I add `http_basic` like this
```ruby
# frozen_string_literal: true

require 'grape'

# api module
module Api
  # api class
  class API < Grape::API
    version 'v1', using: :header, vendor: 'my_api'
    format :json
    prefix :api

    resource :status do
      http_basic do |_username, _password|
        true
      end

      desc 'Some description'
      get do
        Time.now
      end
    end
  end
end
```

any request causes an `ArgumentError`
```
ArgumentError: wrong number of arguments (given 2, expected 1)
	/home/henning/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/middleware/auth/base.rb:13:in `initialize'
	/home/henning/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:158:in `new'
	/home/henning/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:158:in `block in use'
(...)
```

Both examples, with and without `http_basic`, seem to work fine with Ruby 2.7.2. I'd assume it's the same for `http_digest`, but I didn't test that.

**Comment by dblock** [comment]
Would you mind turning these into a spec? Maybe a fix? We have Ruby 3 in CI already.

**Comment by myxoh** [comment]
Hey - I just checked ! `1.5.1` is not compatible with Ruby 3 - however this example works fine with `master` (I think we haven't released this yet?).

Could you confirm?

**Comment by hkockerbeck** [comment]
I just tried the above example with the current `master`, and it seems to work fine.

**Comment by dblock** [comment]
I'll close this.
