### ISSUE TITLE
`mount': wrong number of arguments (given 0, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by matiasasis** [ruby-grape/grape#2156]
Hey Grape Team!

I'm trying to do a grape ror api. And I'm getting this error (at the bottom).

This is my setup:

Gemfile:
```
ruby '3.0.0'

gem 'active_interaction', '~> 4.0'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 6.1.1'
gem 'grape', '~> 1.5.1'
gem 'grape_on_rails_routes'
```

routes.rb:
```
Rails.application.routes.draw do
  mount Main::API, at: '/'
end
```

app/api/main/api.rb:
```
module Main
  class API < Grape::API
    prefix :api
    version :v1, using: :path
    format :json

    mount Stats::API
  end
end
```

app/api/stats/api.rb
```
module Stats
  class API < Grape::API

    resources :stats do
      mount Stats::Summary
    end
  end
end
```

app/api/stats/summary.rb
```
module Stats
  class Summary < Grape::API

    get do
      puts "hello"
    end

  end
end
```

config/initializers/inflections.rb:
```
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym 'API'
end
```

And I'm getting the following error:
```
/Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/dsl/routing.rb:82:in `mount': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/dsl/routing.rb:86:in `block in mount'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/dsl/routing.rb:84:in `each_pair'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/dsl/routing.rb:84:in `mount'
	from /Users/mati/work/rigup/agent-k/app/api/stats/api.rb:7:in `block in <class:API>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api/instance.rb:120:in `instance_eval'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api/instance.rb:120:in `block in evaluate_as_instance_with_configuration'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/util/lazy_block.rb:11:in `evaluate_from'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api/instance.rb:127:in `evaluate_as_instance_with_configuration'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api/instance.rb:107:in `block in nest'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api/instance.rb:107:in `each'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api/instance.rb:107:in `nest'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/dsl/routing.rb:172:in `block in namespace'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/dsl/settings.rb:160:in `within_namespace'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/dsl/routing.rb:169:in `namespace'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api.rb:155:in `replay_step_on'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api.rb:147:in `block in add_setup'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api.rb:146:in `each'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api.rb:146:in `add_setup'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.1/lib/grape/api.rb:42:in `block (2 levels) in override_all_methods!'
	from /Users/mati/work/rigup/agent-k/app/api/stats/api.rb:6:in `<class:API>'
	from /Users/mati/work/rigup/agent-k/app/api/stats/api.rb:4:in `<module:Stats>'
	from /Users/mati/work/rigup/agent-k/app/api/stats/api.rb:3:in `<main>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	from /Users/mati/work/rigup/agent-k/app/api/main/api.rb:15:in `<class:API>'
	from /Users/mati/work/rigup/agent-k/app/api/main/api.rb:4:in `<module:Main>'
	from /Users/mati/work/rigup/agent-k/app/api/main/api.rb:3:in `<main>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	from /Users/mati/work/rigup/agent-k/config/routes.rb:6:in `block in <main>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:427:in `instance_exec'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:409:in `draw'
	from /Users/mati/work/rigup/agent-k/config/routes.rb:3:in `<main>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/application/routes_reloader.rb:47:in `block in load_paths'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/application/routes_reloader.rb:47:in `each'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/application/routes_reloader.rb:47:in `load_paths'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/application/routes_reloader.rb:21:in `reload!'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/application/routes_reloader.rb:35:in `block in updater'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/file_update_checker.rb:83:in `execute'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/application/routes_reloader.rb:10:in `execute'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/application/finisher.rb:195:in `block in <module:Finisher>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `run'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/application.rb:384:in `initialize!'
	from /Users/mati/work/rigup/agent-k/config/environment.rb:7:in `<main>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	from config.ru:5:in `block in <main>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/commands/server/server_command.rb:37:in `start'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/commands/server/server_command.rb:135:in `perform'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/command/base.rb:69:in `perform'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/command.rb:50:in `invoke'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.1/lib/rails/commands.rb:18:in `<main>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /Users/mati/work/rigup/agent-k/bin/rails:5:in `<top (required)>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	from /Users/mati/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from <internal:/Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/mati/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/mati/work/rigup/agent-k/bin/spring:10:in `block in <top (required)>'
	from <internal:kernel>:90:in `tap'
	from /Users/mati/work/rigup/agent-k/bin/spring:7:in `<top (required)>'
	from bin/rails:2:in `load'
	from bin/rails:2:in `<main>'
```

**Comment by dblock** [comment]
Looks odd. Does this reproduce in a spec in Grape HEAD?

**Comment by matiasasis** [comment]
@dblock Thanks for your fast response!

Works pointing to HEAD:

`gem 'grape', :github => 'ruby-grape/grape', :ref => 'HEAD'`

Does not work with `1.5.1` and plain mount.

What does work with `1.5.1` is a plain endpoint without mount:

```
module Main
  class API < Grape::API
    prefix :api
    version :v1, using: :path
    format :json

    get :hello do
      return "hello"
    end

    # mount Stats::Summary
  end
end
```

**Comment by dblock** [comment]
So we already fixer this? I would bisect to a fix, and ensure that we have a spec that covers it.

**Comment by dblock** [comment]
I bet it's #2142, and it works with older versions of Ruby < 3

**Comment by matiasasis** [comment]
Yes, seems to be already fixed on the newest version, will use HEAD till new release, thanks!

**Comment by igor-drozdov** [comment]
@dblock Thanks for sorting out all these issues, don't mean to bother, but when a new release is going to be cut?

**Comment by dnesteryuk** [comment]
@igor-drozdov I am going to release the next version this weekend :slightly_smiling_face:

**Comment by igor-drozdov** [comment]
@dnesteryuk sounds great, thanks!
