### ISSUE TITLE
truffleruby-head build is broken

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#2212]
CI is failing on truffleruby-head

### Locally

```
truffleruby 22.1.0-dev-20f07ecc, like ruby 3.0.2, GraalVM CE Native [x86_64-linux]
```

```
  166) Grape::Validations::Validators::AllowBlankValidator in an optional group as an optional param accepts a missing group, even with a disallwed blank param
       Failure/Error: instance_variable_set(:"#{TestProf::LetItBe::PREFIX}#{identifier}", instance_exec(&block))

       NameError:
         `@😸app' is not allowable as an instance variable name
       # /home/ubuntu/.rvm/gems/truffleruby-head/gems/test-prof-1.0.7/lib/test_prof/recipes/rspec/let_it_be.rb:90:in `instance_variable_set'
       # /home/ubuntu/.rvm/gems/truffleruby-head/gems/test-prof-1.0.7/lib/test_prof/recipes/rspec/let_it_be.rb:90:in `block in let_it_be'
       # /home/ubuntu/.rvm/gems/truffleruby-head/gems/test-prof-1.0.7/lib/test_prof/recipes/rspec/before_all.rb:26:in `instance_eval'
       # /home/ubuntu/.rvm/gems/truffleruby-head/gems/test-prof-1.0.7/lib/test_prof/recipes/rspec/before_all.rb:26:in `block (2 levels) in before_all'
       # /home/ubuntu/.rvm/gems/truffleruby-head/gems/test-prof-1.0.7/lib/test_prof/before_all.rb:24:in `begin_transaction'
       # /home/ubuntu/.rvm/gems/truffleruby-head/gems/test-prof-1.0.7/lib/test_prof/recipes/rspec/before_all.rb:25:in `block in before_all'
```

### CI

https://github.com/ruby-grape/grape/runs/4646048378?check_suite_focus=true got killed

**Comment by eregon** [comment]
Same as https://github.com/oracle/truffleruby/issues/2462

**Comment by duffn** [comment]
CI is passing now. https://github.com/ruby-grape/grape/runs/6892432974?check_suite_focus=true
