### ISSUE TITLE
Incompatibility of grape 1.5.3 with Rails 6.1

### ISSUE THREAD

**Issue by VikasKumar190** [ruby-grape/grape#2257]
Rails version : 6.1.4.7
Grape version: 1.5.3, (also tried with version 1.3.3)

Following is the error whenever a grape api endpoint is hit

```
12:08:45 web.1         | ArgumentError (missing keyword: :header):
12:08:45 web.1         |   
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/request_id.rb:18:in `initialize'
12:08:45 web.1         | rack (2.2.3) lib/rack/builder.rb:158:in `new'
12:08:45 web.1         | rack (2.2.3) lib/rack/builder.rb:158:in `block in use'
12:08:45 web.1         | rack (2.2.3) lib/rack/builder.rb:235:in `block in to_app'
12:08:45 web.1         | rack (2.2.3) lib/rack/builder.rb:235:in `each'
12:08:45 web.1         | rack (2.2.3) lib/rack/builder.rb:235:in `inject'
12:08:45 web.1         | rack (2.2.3) lib/rack/builder.rb:235:in `to_app'
12:08:45 web.1         | grape (1.5.3) lib/grape/endpoint.rb:323:in `build_stack'
12:08:45 web.1         | grape (1.5.3) lib/grape/endpoint.rb:355:in `block in lazy_initialize!'
12:08:45 web.1         | grape (1.5.3) lib/grape/endpoint.rb:351:in `synchronize'
12:08:45 web.1         | grape (1.5.3) lib/grape/endpoint.rb:351:in `lazy_initialize!'
12:08:45 web.1         | grape (1.5.3) lib/grape/endpoint.rb:224:in `call'
12:08:45 web.1         | grape (1.5.3) lib/grape/router/route.rb:58:in `exec'
12:08:45 web.1         | grape (1.5.3) lib/grape/router.rb:116:in `process_route'
12:08:45 web.1         | grape (1.5.3) lib/grape/router.rb:72:in `block in identity'
12:08:45 web.1         | grape (1.5.3) lib/grape/router.rb:91:in `transaction'
12:08:45 web.1         | grape (1.5.3) lib/grape/router.rb:70:in `identity'
12:08:45 web.1         | grape (1.5.3) lib/grape/router.rb:55:in `block in call'
12:08:45 web.1         | grape (1.5.3) lib/grape/router.rb:132:in `with_optimization'
12:08:45 web.1         | grape (1.5.3) lib/grape/router.rb:54:in `call'
12:08:45 web.1         | grape (1.5.3) lib/grape/api/instance.rb:167:in `call'
12:08:45 web.1         | grape (1.5.3) lib/grape/api/instance.rb:71:in `call!'
12:08:45 web.1         | grape (1.5.3) lib/grape/api/instance.rb:66:in `call'
12:08:45 web.1         | grape (1.5.3) lib/grape/api.rb:68:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/routing/mapper.rb:49:in `serve'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/journey/router.rb:32:in `each'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/journey/router.rb:32:in `serve'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/routing/route_set.rb:842:in `call'
12:08:45 web.1         | rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
12:08:45 web.1         | rack (2.2.3) lib/rack/etag.rb:27:in `call'
12:08:45 web.1         | rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
12:08:45 web.1         | rack (2.2.3) lib/rack/head.rb:12:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
12:08:45 web.1         | rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
12:08:45 web.1         | rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/cookies.rb:689:in `call'
12:08:45 web.1         | activerecord (6.1.4.7) lib/active_record/migration.rb:601:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
12:08:45 web.1         | activesupport (6.1.4.7) lib/active_support/callbacks.rb:98:in `run_callbacks'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
12:08:45 web.1         | railties (6.1.4.7) lib/rails/rack/logger.rb:37:in `call_app'
12:08:45 web.1         | railties (6.1.4.7) lib/rails/rack/logger.rb:26:in `block in call'
12:08:45 web.1         | activesupport (6.1.4.7) lib/active_support/tagged_logging.rb:99:in `block in tagged'
12:08:45 web.1         | activesupport (6.1.4.7) lib/active_support/tagged_logging.rb:37:in `tagged'
12:08:45 web.1         | activesupport (6.1.4.7) lib/active_support/tagged_logging.rb:99:in `tagged'
12:08:45 web.1         | railties (6.1.4.7) lib/rails/rack/logger.rb:26:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/request_id.rb:26:in `call'
12:08:45 web.1         | rack (2.2.3) lib/rack/method_override.rb:24:in `call'
12:08:45 web.1         | rack (2.2.3) lib/rack/runtime.rb:22:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/static.rb:24:in `call'
12:08:45 web.1         | rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
12:08:45 web.1         | actionpack (6.1.4.7) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
12:08:45 web.1         | railties (6.1.4.7) lib/rails/engine.rb:539:in `call'
12:08:45 web.1         | passenger (5.3.2) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
12:08:45 web.1         | passenger (5.3.2) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
12:08:45 web.1         | passenger (5.3.2) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
12:08:45 web.1         | passenger (5.3.2) src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
12:08:45 web.1         | passenger (5.3.2) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

Any hints what could be going wrong here?

**Comment by dblock** [comment]
I don't remember seeing this one. We do have integration tests for Rails 6.1 (see https://github.com/ruby-grape/grape/blob/master/Appraisals), so this is something more specific to your application. See what's being initialized in lib/action_dispatch/middleware/request_id.rb? I usually just do something as dumb as `bundle show action_dispatch` and just add some puts above that call locally :)

**Comment by VikasKumar190** [comment]
@dblock, Thanks for the hints. I realised what was going wrong. We were using `ActionDispatch::RequestId` middleware in the `api.rb` file. So, one of the statements in our `api.rb` is :
```
use ActionDispatch::RequestId
```
Apparently, the middleware has changed its implementation from rails 6.0 to 6.1 and expects you to also pass in header name that will be used to add request id. So, the statement in the `api.rb` file needs to be changed to something like:
```
use ActionDispatch::RequestId, header: "X-Request-Id"
```
I think we missed this out and ended up opening this ticket.
So, this is not a bug on Grape, we were using ActionDispatch middleware incorrectly.
