### ISSUE TITLE
Some tests fail with `uninitialized constant Grape::Validations::Types::BigDecimal`

### ISSUE THREAD

**Issue by duffn** [ruby-grape/grape#2260]
Some test matrix combinations fail with the below error.

- Example as I'm working on (https://github.com/ruby-grape/grape/issues/2061): https://github.com/duffn/grape/runs/6865569857?check_suite_focus=true (see which tests fail here)
- Failing on previous PR: https://github.com/ruby-grape/grape/runs/6166521301?check_suite_focus=true

```
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/ruby -I/home/runner/work/grape/grape/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/lib:/home/runner/work/grape/grape/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.11.0/lib /home/runner/work/grape/grape/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.11.0/exe/rspec --pattern spec/\*\*/\*_spec.rb  --exclude-pattern spec/integration/\*\*/\*_spec.rb
An error occurred while loading spec_helper.
Failure/Error: BigDecimal,
NameError:
  uninitialized constant Grape::Validations::Types::BigDecimal
# ./lib/grape/validations/types.rb:25:in `<module:Types>'
# ./lib/grape/validations/types.rb:18:in `<module:Validations>'
# ./lib/grape/validations/types.rb:[7](https://github.com/duffn/grape/runs/6865569857?check_suite_focus=true#step:4:8):in `<module:Grape>'
# ./lib/grape/validations/types.rb:6:in `<top (required)>'
# ./lib/grape.rb:240:in `require'
# ./lib/grape.rb:240:in `<module:Validations>'
# ./lib/grape.rb:227:in `<module:Grape>'
# ./lib/grape.rb:30:in `<top (required)>'
# ./spec/spec_helper.rb:7:in `require'
# ./spec/spec_helper.rb:7:in `<top (required)>'
No examples found.
No examples found.
Finished in 0.00003 seconds (files took 0.7[25](https://github.com/duffn/grape/runs/6865569857?check_suite_focus=true#step:4:26)66 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
Finished in 0.00003 seconds (files took 0.72566 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by dblock** [comment]
I think this is https://github.com/ruby/bigdecimal/issues/127, or similar. Explicitly requiring `bigdecimal` seems to work, https://github.com/dblock/grape/actions/runs/2491398080.

https://github.com/ruby-grape/grape/pull/2263
