### ISSUE TITLE
NameError: uninitialized constant Dry::Core::Container::Mixin in v1.7.0

### ISSUE THREAD

**Issue by wata727** [ruby-grape/grape#2305]
After upgrading to v1.7.0, an error such as load failure occurred on some servers in rare cases. A similar error did not occur with v1.6.2. Below is the stack trace without the application code:

```
NameError: uninitialized constant Dry::Core::Container::Mixin
  from dry-types (1.7.0) lib/dry/types/container.rb:9:in `<class:Container>'
  from dry-types (1.7.0) lib/dry/types/container.rb:8:in `<module:Types>'
  from dry-types (1.7.0) lib/dry/types/container.rb:4:in `<module:Dry>'
  from dry-types (1.7.0) lib/dry/types/container.rb:3:in `<main>'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from zeitwerk (2.6.6) lib/zeitwerk/kernel.rb:30:in `require'
  from dry-types (1.7.0) lib/dry/types.rb:83:in `container'
  from dry-types (1.7.0) lib/dry/types.rb:105:in `register'
  from dry-types (1.7.0) lib/dry/types/core.rb:49:in `block in <module:Types>'
  from dry-types (1.7.0) lib/dry/types/core.rb:47:in `each'
  from dry-types (1.7.0) lib/dry/types/core.rb:47:in `<module:Types>'
  from dry-types (1.7.0) lib/dry/types/core.rb:4:in `<module:Dry>'
  from dry-types (1.7.0) lib/dry/types/core.rb:3:in `<main>'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from zeitwerk (2.6.6) lib/zeitwerk/kernel.rb:38:in `require'
  from dry-types (1.7.0) lib/dry/types.rb:258:in `<main>'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from zeitwerk (2.6.6) lib/zeitwerk/kernel.rb:38:in `require'
  from dry-types (1.7.0) lib/dry-types.rb:3:in `<main>'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from zeitwerk (2.6.6) lib/zeitwerk/kernel.rb:38:in `require'
  from grape (1.7.0) lib/grape/validations/types/dry_type_coercer.rb:3:in `<main>'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from zeitwerk (2.6.6) lib/zeitwerk/kernel.rb:38:in `require'
  from grape (1.7.0) lib/grape/validations/types.rb:186:in `create_coercer_instance'
  from grape (1.7.0) lib/grape/validations/types.rb:162:in `block in build_coercer'
  from grape (1.7.0) lib/grape/validations/types.rb:195:in `cache_instance'
  from grape (1.7.0) lib/grape/validations/types.rb:161:in `build_coercer'
  from grape (1.7.0) lib/grape/validations/validators/coerce_validator.rb:13:in `initialize'
  from grape (1.7.0) lib/grape/validations/validator_factory.rb:7:in `new'
  from grape (1.7.0) lib/grape/validations/validator_factory.rb:7:in `create_validator'
  from grape (1.7.0) lib/grape/endpoint.rb:351:in `block in run_validators'
  from grape (1.7.0) lib/grape/endpoint.rb:351:in `map'
  from grape (1.7.0) lib/grape/endpoint.rb:351:in `run_validators'
  from grape (1.7.0) lib/grape/endpoint.rb:259:in `block in run'
  from activesupport (6.0.5) lib/active_support/notifications.rb:182:in `instrument'
  from grape (1.7.0) lib/grape/endpoint.rb:241:in `run'
  from grape (1.7.0) lib/grape/endpoint.rb:316:in `block in build_stack'
  from newrelic_rpm (8.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from grape (1.7.0) lib/grape/middleware/base.rb:36:in `call!'
  from grape (1.7.0) lib/grape/middleware/base.rb:29:in `call'
  from newrelic_rpm (8.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from grape (1.7.0) lib/grape/middleware/base.rb:36:in `call!'
  from grape (1.7.0) lib/grape/middleware/base.rb:29:in `call'
  from newrelic_rpm (8.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from grape (1.7.0) lib/grape/middleware/error.rb:39:in `block in call!'
  from grape (1.7.0) lib/grape/middleware/error.rb:38:in `catch'
  from grape (1.7.0) lib/grape/middleware/error.rb:38:in `call!'
  from grape (1.7.0) lib/grape/middleware/base.rb:29:in `call'
  from newrelic_rpm (8.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack (2.1.4.1) lib/rack/head.rb:14:in `call'
  from newrelic_rpm (8.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from grape (1.7.0) lib/grape/endpoint.rb:225:in `call!'
  from grape (1.7.0) lib/grape/endpoint.rb:219:in `call'
  from grape (1.7.0) lib/grape/router/route.rb:58:in `exec'
  from grape (1.7.0) lib/grape/router.rb:120:in `process_route'
  from grape (1.7.0) lib/grape/router.rb:74:in `block in identity'
  from grape (1.7.0) lib/grape/router.rb:94:in `transaction'
  from grape (1.7.0) lib/grape/router.rb:72:in `identity'
  from grape (1.7.0) lib/grape/router.rb:56:in `block in call'
  from grape (1.7.0) lib/grape/router.rb:136:in `with_optimization'
  from grape (1.7.0) lib/grape/router.rb:55:in `call'
  from grape (1.7.0) lib/grape/api/instance.rb:165:in `call'
  from newrelic_rpm (8.14.0) lib/new_relic/agent/instrumentation/grape/prepend.rb:10:in `call'
  from grape (1.7.0) lib/grape/api/instance.rb:70:in `call!'
  from grape (1.7.0) lib/grape/api/instance.rb:65:in `call'
  from grape (1.7.0) lib/grape/api.rb:81:in `call'
  from actionpack (6.0.5) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
  from actionpack (6.0.5) lib/action_dispatch/routing/mapper.rb:48:in `serve'
  from actionpack (6.0.5) lib/action_dispatch/journey/router.rb:49:in `block in serve'
  from actionpack (6.0.5) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (6.0.5) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (6.0.5) lib/action_dispatch/routing/route_set.rb:834:in `call'
  from newrelic_rpm (8.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack-attack (6.6.1) lib/rack/attack.rb:127:in `call'
  from newrelic_rpm (8.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from newrelic_rpm (8.14.0) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  from newrelic_rpm (8.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from newrelic_rpm (8.14.0) lib/new_relic/rack/browser_monitoring.rb:38:in `traced_call'
  from newrelic_rpm (8.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'

... <snip> ...
```

The error is happening here. This means that `include Core::Container::Mixin` fails to require dry-core gem.
https://github.com/dry-rb/dry-types/blob/v1.7.0/lib/dry/types/container.rb#L9

Although it has not been investigated in detail, the cause may be the autoload introduced in v1.7.0 https://github.com/ruby-grape/grape/pull/2222

The strange thing is that the error doesn't always occur, but rarely. Perhaps there should be a pattern that occurs under certain conditions, but unfortunately I could not identify the conditions. Could you help me investigate the cause of this?

## Environment

- Rails 6.0.5
  - `config.autoloader = :zeitwerk`
- Ruby 2.7.6
- Zeitwerk 2.6.6

**Comment by dblock** [comment]
Does an explicit `require 'dry-core'` help?

**Comment by wata727** [comment]
Probably yes, but it's good to have all required gems loaded with `require 'grape'`.
As a workaround, we rolled back to v1.6.2 in our environment.

**Comment by dblock** [comment]
@wata727 I agree, it shouldn't be necessary. I was only trying to narrow down why this could be happening.

**Comment by wata727** [comment]
Thank you for your help. I did a little research, so I'll share the results.

dry-types/dry-core seems to use Zeitwerk for autoloading:
https://github.com/dry-rb/dry-types/blob/v1.7.0/lib/dry/types.rb#L62
https://github.com/dry-rb/dry-core/blob/v1.0.0/lib/dry/core.rb#L29

In fact, autoload seems to work correctly in dry-types.

```
  from dry-types (1.7.0) lib/dry/types/container.rb:3:in `<main>'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from bootsnap (1.15.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  from zeitwerk (2.6.6) lib/zeitwerk/kernel.rb:30:in `require'
  from dry-types (1.7.0) lib/dry/types.rb:83:in `container'
```

https://github.com/dry-rb/dry-types/blob/v1.7.0/lib/dry/types.rb#L83
https://github.com/dry-rb/dry-types/blob/v1.7.0/lib/dry/types/container.rb#L3

So, the cause of the issue is that `Core::Container::Mixin` does not trigger autoloading dry-core by Zeitwerk.
https://github.com/dry-rb/dry-types/blob/v1.7.0/lib/dry/types/container.rb#L9

The autoloader inside dry-core is set up when `require dry/core` is called. I thought maybe there are paths where this is not called, but it is called explicitly in dry-types.
https://github.com/dry-rb/dry-types/blob/v1.7.0/lib/dry/types.rb#L10

From the stack trace it's also clear that this is called.

```
  from dry-types (1.7.0) lib/dry/types.rb:258:in `<main>'
```

Based on the above, this issue may not be in grape, but dry-types. But since v1.7.0 I started getting this error, so it may not be unrelated.

Possible causes are:

- Multithreading issues
  - In our environment, we run Puma with 12 threads. Depending on the execution path, `Core::Container::Mixin` may be evaluated before Zeitwerk autoloader setup inside dry-core is complete. But I'm not sure if that really happens.
- Zeitwerk issues
  - Zeitwerk usage in dry-types/dry-core may be wrong, or unknown bugs in Zeitwerk may be encountered.
- Bootsnap issues
  - Our application uses [Bootsnap](https://github.com/Shopify/bootsnap). The cached read optimization may be leading to incorrect behavior.

I plan to investigate these possibilities. If you have any other good ideas, please let me know.

**Comment by dblock** [comment]
I think you're on the right track wrt multi-threading. It's probably a race condition in code that didn't expect to run multithreaded.

**Comment by wata727** [comment]
We've confirmed that a similar error is fixed after enabling eager loading as below:

```ruby
module MyApp
  class Application < Rails::Application
    config.after_initialize do
      # eager loading: https://github.com/ruby-grape/grape#all
      MyApp::API.compile!
    end
  end
end
```

Thank you for your help and for maintaining this gem.

**Comment by dblock** [comment]
I do think we have a bug that needs fixing. I won't reopen this, but if someone wants to take on adding multithreaded tests, we'll probably be able to reproduce.
