### ISSUE TITLE
Ruby 3.3 && cookiejar = ArgumentError

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2394]
While testing Ruby 3.3, `cookiejar` doesn't seem to work. `rspec` fails with
```
ArgumentError:
  wrong number of arguments (given 3, expected 1..2)
# /usr/local/bundle/gems/ruby/3.3.0/gems/cookiejar-0.3.3/lib/cookiejar/cookie_validation.rb:48:in `initialize'
# /usr/local/bundle/gems/ruby/3.3.0/gems/cookiejar-0.3.3/lib/cookiejar/cookie_validation.rb:48:in `new'
# /usr/local/bundle/gems/ruby/3.3.0/gems/cookiejar-0.3.3/lib/cookiejar/cookie_validation.rb:48:in `<module:CookieValidation>'
# /usr/local/bundle/gems/ruby/3.3.0/gems/cookiejar-0.3.3/lib/cookiejar/cookie_validation.rb:25:in `<module:CookieJar>'
# /usr/local/bundle/gems/ruby/3.3.0/gems/cookiejar-0.3.3/lib/cookiejar/cookie_validation.rb:5:in `<top (required)>'
# /usr/local/bundle/gems/ruby/3.3.0/gems/cookiejar-0.3.3/lib/cookiejar/cookie.rb:3:in `<top (required)>'
# /usr/local/bundle/gems/ruby/3.3.0/gems/cookiejar-0.3.3/lib/cookiejar.rb:1:in `<top (required)>'
# /usr/local/bundle/gems/bundler-2.4.22/lib/bundler.rb:187:in `require'
# ./spec/spec_helper.rb:9:in `<top (required)>'
```

It's only used in test and we can easily isolate the specs.

**Comment by dblock** [comment]
Is this https://github.com/dwaite/cookiejar? It was archived a while ago, so I think it's time to move on.
