### ISSUE TITLE
uninitialized constant Grape::ContentTypes::CONTENT_TYPES

### ISSUE THREAD

**Issue by MirkoCindric** [ruby-grape/grape#2499]
Recently bumped to ruby 3.1.3 and using grape 1.70 when i go to load grape swagger i get 

uninitialized constant Grape::ContentTypes::CONTENT_TYPES

```ers_session=Lx0l%2FGed4QKW3%2FoeMPFMMaLMQUt0mptHk%2FrPAMiK7Sujx638MEMi0p%2B%2BjnXeG%2B4d75LiZfbXtQAZRSXRz8Bv541v1oAQr8YH%2FQWIHaDsE5NYJn5TMr7x6SsgmtK1%2BRMZpwLpiKhB4QIZ1rT6JpbMHLpdowbWj130TWcTfKdZVhwReqQqjXYj7PnsgUndF5tufQVT%2B6hsFvFpTDoW5Hp1PgYQA1zH64gUrR8S8XCukdb%2FcGQauXDzxY%2FW4RlWtizLyAHqDqsIqIESsuUevNfellX%2BMLgL0uD6VwJkWN2thxsT4IG2JFI%3D--BPulbbh3U5j%2FO8AG--A7wf4%2B6yWBPbSWyVwA3vkQ%3D%3D; _devise-session=36771b4aa4b541a1476ded3139e4db17"} host=localhost ip=::1 params={} response=uninitialized constant Grape::ContentTypes::CONTENT_TYPES ua=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
[2024-09-19 15:35:12 +1000] INFO -- 500 -- db=0 total=10.98 view=10.98 -- GET /api/swagger_doc host=localhost params={}
/Users/mirko/.gem/ruby/3.1.2/gems/grape-swagger-2.1.0/lib/grape-swagger/doc_methods/produces_consumes.rb:10:in `block in call'
/Users/mirko/.gem/ruby/3.1.2/gems/grape-swagger-2.1.0/lib/grape-swagger/doc_methods/produces_consumes.rb:10:in `map'
/Users/mirko/.gem/ruby/3.1.2/gems/grape-swagger-2.1.0/lib/grape-swagger/doc_methods/produces_consumes.rb:10:in `call'
/Users/mirko/.gem/ruby/3.1.2/gems/grape-swagger-2.1.0/lib/grape-swagger/endpoint.rb:160:in `produces_object'
/Users/mirko/.gem/ruby/3.1.2/gems/grape-swagger-2.1.0/lib/grape-swagger/endpoint.rb:120:in `method_object'
/Users/mirko/.gem/ruby/3.1.2/gems/grape-swagger-2.1.0/lib/grape-swagger/endpoint.rb:104:in `block in path_item'
/Users/mirko/.gem/ruby/3.1.2/gems/grape-swagger-2.1.0/lib/grape-swagger/endpoint.rb:98:in `each'
/Users/mirko/.gem/ruby/3.1.2/gems/grape-swagger-2.1.0/lib/grape-swagger/endpoint.rb:98:in `path_item'
/Users/mirko/.gem/ruby/3.1.2/gems/grape-swagger-2.1.0/lib/grape-swagger/endpoint.rb:84:in `block in path_and_definition_objects'
/Users/mirko/.gem/ruby/3.1.2/gems/grape-swagger-2.1.0/lib/grape-swagger/endpoint.rb:83:in `each_value'```

**Comment by dblock** [comment]
This is https://github.com/ruby-grape/grape-swagger/issues/939, closing.
