### ISSUE TITLE
undefined method `parser_for' for Grape::Parser::Base:Module

### ISSUE THREAD

**Issue by cvengros** [ruby-grape/grape#541]
When I deploy my app to heroku, I sometimes get an error saying

```
undefined method `parser_for' for Grape::Parser::Base:Module
```

This usually happens when the app processes the first request after I push a new version to my heroku git, it also happens randomly every now and then without pushing a new version.

I couldn't reproduce this locally. 
Stack trace:

```
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/middleware/formatter.rb:69:in `read_rack_input'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/middleware/formatter.rb:56:in `read_body_input'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/middleware/formatter.rb:24:in `before'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/middleware/base.rb:23:in `call!'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/middleware/base.rb:18:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/middleware/error.rb:26:in `block in call!'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/middleware/error.rb:25:in `catch'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/middleware/error.rb:25:in `call!'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/middleware/base.rb:18:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/endpoint.rb:155:in `call!'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/endpoint.rb:145:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
/app/vendor/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
/app/vendor/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
/app/vendor/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
/app/vendor/bundle/ruby/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/api.rb:525:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/api.rb:42:in `call!'
/app/vendor/bundle/ruby/1.9.1/gems/grape-0.6.1/lib/grape/api.rb:38:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
/app/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
/app/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rack-ssl-1.3.3/lib/rack/ssl.rb:27:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

Any ideas?

**Comment by dblock** [comment]
Closing, I believe this is fixed.
